{% set name = "frictionqpotfem" %}
{% set version = "0.4.1" %}
{% set sha256 = "36a356aac76ae0a40e0d0639c8a4375cb5fa1caa81d1c58116a4ca32ab53d993" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tdegeus/FrictionQPotFEM/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
    - goosefem
    - gmatelastoplasticqpot
    - xtensor
    - fmt
  run:
    - goosefem
    - gmatelastoplasticqpot
    - xtensor
    - fmt

test:
  commands:
    - test -d ${PREFIX}/include/FrictionQPotFEM  # [unix]
    - test -f ${PREFIX}/include/FrictionQPotFEM/UniformSingleLayer2d.h  # [unix]
    - test -f ${PREFIX}/lib/cmake/FrictionQPotFEM/FrictionQPotFEMConfig.cmake  # [unix]
    - if exist %LIBRARY_PREFIX%\include\FrictionQPotFEM\UniformSingleLayer2d.h (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\cmake\FrictionQPotFEMConfig.cmake (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/tdegeus/FrictionQPotFEM
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Library to run friction simulations based on "GMatElastoPlasticQPot" and "GooseFEM".
  description: Library to run friction simulations based on "GMatElastoPlasticQPot" and "GooseFEM".
  doc_url: https://github.com/tdegeus/FrictionQPotFEM
  dev_url: https://github.com/tdegeus/FrictionQPotFEM

extra:
  recipe-maintainers:
    - tdegeus
