{% set org = "tdegeus" %}
{% set name = "FrictionQPotFEM" %}
{% set version = "0.12.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ org }}/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 159d6e1a5081e85b4e6aad776b829ed115ef93182f13d76b8327df27f6f02c73

build:
  number: 0
  script_env: SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  skip: true  # [py<39 and osx and not x86_64]

outputs:

  - name: {{ name|lower }}

    script: install.sh  # [unix]
    script: install.bat  # [win]

    requirements:
      build:
        - python                                 # [build_platform != target_platform]
        - {{ compiler('cxx') }}
        - cmake
        - make  # [unix]
      host:
        - python
        - xtensor
        - qpot
        - goosefem
        - gmatelastoplasticqpot
      run:
        - xtensor
        - qpot
        - goosefem
        - gmatelastoplasticqpot

    test:
      commands:
        - test -d ${PREFIX}/include/{{ name }}  # [unix]
        - test -f ${PREFIX}/include/{{ name }}/UniformSingleLayer2d.h  # [unix]
        - test -f ${PREFIX}/lib/cmake/{{ name }}/{{ name }}Config.cmake  # [unix]
        - if exist %LIBRARY_PREFIX%\include\{{ name }}\UniformSingleLayer2d.h (exit 0) else (exit 1)  # [win]
        - if exist %LIBRARY_PREFIX%\lib\cmake\{{ name }}Config.cmake (exit 0) else (exit 1)  # [win]

  - name: python-{{ name|lower }}

    script: install_python.sh  # [unix]
    script: install_python.bat  # [win]

    requirements:
      build:
        - python                              # [build_platform != target_platform]
        - cross-python_{{ target_platform }}  # [build_platform != target_platform]
        - numpy                               # [build_platform != target_platform]
        - setuptools_scm                      # [build_platform != target_platform]
        - {{ compiler('cxx') }}
        - cmake
        - ninja
      host:
        - setuptools_scm
        - xtensor
        - qpot
        - goosefem
        - gmatelastoplasticqpot
        - python
        - numpy
        - pip
        - pybind11
        - xtensor-python
        - pyxtensor
        - qpot
        - goosefem
      run:
        - python

    test:
      imports:
        - {{ name }}
      commands:
        - pip check
      requires:
        - pip

about:
  home: https://github.com/{{ org }}/{{ name }}
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Library to run friction simulations based on "GMatElastoPlasticQPot" and "GooseFEM".
  description: Library to run friction simulations based on "GMatElastoPlasticQPot" and "GooseFEM".
  doc_url: https://{{ org }}.github.io/{{ name }}
  dev_url: https://github.com/{{ org }}/{{ name }}

extra:
  recipe-maintainers:
    - tdegeus
