{% set org = "tdegeus" %}
{% set name = "FrictionQPotFEM" %}
{% set version = "0.17.1" %}

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  url: https://github.com/{{ org }}/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: a95718e307f5dee4abee6d07f08a6384039acd4429b1d8b722326eb2f84b3d91

build:
  number: 0
  script_env: SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}

outputs:

  - name: {{ name|lower }}

    script: install.sh  # [unix]
    script: install.bat  # [win]

    requirements:
      build:
        - {{ compiler('cxx') }}
        - cmake
        - make  # [unix]
      host:
        - gmatelastoplasticqpot
        - goosefem
        - qpot
        - xtensor
      run:
        - gmatelastoplasticqpot
        - goosefem
        - qpot
        - xtensor

    test:
      commands:
        - test -d ${PREFIX}/include/{{ name }}  # [unix]
        - test -f ${PREFIX}/include/{{ name }}/UniformSingleLayer2d.h  # [unix]
        - test -f ${PREFIX}/lib/cmake/{{ name }}/{{ name }}Config.cmake  # [unix]
        - if exist %LIBRARY_PREFIX%\include\{{ name }}\UniformSingleLayer2d.h (exit 0) else (exit 1)  # [win]
        - if exist %LIBRARY_PREFIX%\lib\cmake\{{ name }}Config.cmake (exit 0) else (exit 1)  # [win]

  - name: python-{{ name|lower }}

    build:   # [python_impl == 'pypy']
      skip: true  # [python_impl == 'pypy']

    script: install_python.sh  # [unix]
    script: install_python.bat  # [win]

    requirements:
      build:
        - python                              # [build_platform != target_platform]
        - cross-python_{{ target_platform }}  # [build_platform != target_platform]
        - numpy *                             # [build_platform != target_platform]
        - setuptools_scm                      # [build_platform != target_platform]
        - {{ compiler('cxx') }}
        - cmake
        - ninja
        - make  # [unix]
      host:
        - gmatelastoplasticqpot
        - goosefem
        - numpy *
        - pip
        - pybind11
        - python
        - qpot
        - scikit-build
        - setuptools_scm
        - xtensor
        - xtensor-python
      run:
        - numpy *
        - python

    test:
      imports:
        - {{ name }}
      commands:
        - pip check
        - python -c "import {{ name }}; {{ name }}.version()"
      requires:
        - pip

about:
  home: https://github.com/{{ org }}/{{ name }}
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Library to run friction simulations based on "GMatElastoPlasticQPot" and "GooseFEM".
  description: Library to run friction simulations based on "GMatElastoPlasticQPot" and "GooseFEM".
  doc_url: https://{{ org }}.github.io/{{ name }}
  dev_url: https://github.com/{{ org }}/{{ name }}

extra:
  recipe-maintainers:
    - tdegeus
