{% set org = "tdegeus" %}
{% set name = "FrictionQPotFEM" %}
{% set version = "0.23.1" %}

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  url: https://github.com/{{ org }}/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: c3b5fe598706be6c694db55e372aefdf5b4ffcfa3fa9f42ddd450b8fa5901816

build:
  number: 0

outputs:

  - name: {{ name|lower }}

    script: install.sh  # [unix]
    script: install.bat  # [win]

    build:
      script_env: SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}

    requirements:
      build:
        - {{ compiler('cxx') }}
        - cmake
        - make  # [unix]
      host:
        - gmatelastoplasticqpot >=0.17.0
        - goosefem >=1.3.0
        - prrng >1.1.0
        - qpot >=0.12.1
        - xtensor >=0.24.1
      run:
        - gmatelastoplasticqpot >=0.17.0
        - goosefem >=1.3.0
        - prrng >1.1.0
        - qpot >=0.12.1
        - xtensor >=0.24.1

    test:
      commands:
        - test -d ${PREFIX}/include/{{ name }}  # [unix]
        - test -f ${PREFIX}/include/{{ name }}/UniformSingleLayer2d.h  # [unix]
        - test -f ${PREFIX}/lib/cmake/{{ name }}/{{ name }}Config.cmake  # [unix]
        - if exist %LIBRARY_PREFIX%\include\{{ name }}\UniformSingleLayer2d.h (exit 0) else (exit 1)  # [win]
        - if exist %LIBRARY_PREFIX%\lib\cmake\{{ name }}Config.cmake (exit 0) else (exit 1)  # [win]

  - name: python-{{ name|lower }}

    script: install_python.sh  # [unix]
    script: install_python.bat  # [win]

    build:
      script_env: SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
      skip: true  # [python_impl == 'pypy']

    requirements:
      build:
        - python                              # [build_platform != target_platform]
        - cross-python_{{ target_platform }}  # [build_platform != target_platform]
        - numpy *                             # [build_platform != target_platform]
        - setuptools_scm                      # [build_platform != target_platform]
        - {{ compiler('cxx') }}
        - cmake
        - make  # [unix]
        - ninja
      host:
        - gmatelastoplasticqpot >=0.17.0
        - goosefem >=1.3.0
        - numpy *
        - pip
        - prrng >1.1.0
        - pybind11
        - pybind11-abi
        - python
        - qpot >=0.12.1
        - scikit-build
        - setuptools_scm
        - xtensor >=0.24.1
        - xtensor-python
      run:
        - numpy *
        - python
        - python-goosefem

    test:
      imports:
        - {{ name }}
      commands:
        - pip check
        - python -c "import {{ name }}; assert {{ name }}.version() == '{{ version }}'"
      requires:
        - pip

about:
  home: https://github.com/{{ org }}/{{ name }}
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Library to run friction simulations based on "GMatElastoPlasticQPot" and "GooseFEM".
  description: Library to run friction simulations based on "GMatElastoPlasticQPot" and "GooseFEM".
  doc_url: https://{{ org }}.github.io/{{ name }}
  dev_url: https://github.com/{{ org }}/{{ name }}

extra:
  recipe-maintainers:
    - tdegeus
